# conda env create -f environment.yml
name: pytao
channels:
  - conda-forge
dependencies:
  - python >=3.9
  - ipykernel
  - ipywidgets
  - jupyterlab
  - bmad >=20250421
  - openPMD-beamphysics
  - numpy
  - h5py
  - pexpect
  - pydantic >=2
  - tqdm
  - pip
  - pip:
      # Install pytao from here.
      - .
